**<center><font size='36'>numpy</font></center>** 

Notes of some useful **<code>numpy</code>** operations.

In [1]:
import numpy as np
import pandas as pd

# Data

## Line into Elements
Read line of data into list of its elements by assigning **<code>delimiter</code>** argument to **<code>int</code>** to specify field with(s)>

In [10]:
# data listed by line
for line in np.genfromtxt("data/pz15_test.txt", dtype=int):
    print(line)

# data listed by list of line elments 
matrix_2d = np.genfromtxt("data/pz15_test.txt", delimiter=1, dtype=int)
matrix_2d

1163751742
1381373672
2136511328
3694931569
7463417111
1319128137
1359912421
3125421639
1293138521
2311944581


array([[1, 1, 6, 3, 7, 5, 1, 7, 4, 2],
       [1, 3, 8, 1, 3, 7, 3, 6, 7, 2],
       [2, 1, 3, 6, 5, 1, 1, 3, 2, 8],
       [3, 6, 9, 4, 9, 3, 1, 5, 6, 9],
       [7, 4, 6, 3, 4, 1, 7, 1, 1, 1],
       [1, 3, 1, 9, 1, 2, 8, 1, 3, 7],
       [1, 3, 5, 9, 9, 1, 2, 4, 2, 1],
       [3, 1, 2, 5, 4, 2, 1, 6, 3, 9],
       [1, 2, 9, 3, 1, 3, 8, 5, 2, 1],
       [2, 3, 1, 1, 9, 4, 4, 5, 8, 1]])

# Routines

## Array creation

### ones
Return a new array of given shape and type, filled with ones.

In [19]:
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

## Padding

In [11]:
# pad a matrix on all four sides with a value
np.pad(matrix_2d, ((1,1),(1,1)))

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 6, 3, 7, 5, 1, 7, 4, 2, 0],
       [0, 1, 3, 8, 1, 3, 7, 3, 6, 7, 2, 0],
       [0, 2, 1, 3, 6, 5, 1, 1, 3, 2, 8, 0],
       [0, 3, 6, 9, 4, 9, 3, 1, 5, 6, 9, 0],
       [0, 7, 4, 6, 3, 4, 1, 7, 1, 1, 1, 0],
       [0, 1, 3, 1, 9, 1, 2, 8, 1, 3, 7, 0],
       [0, 1, 3, 5, 9, 9, 1, 2, 4, 2, 1, 0],
       [0, 3, 1, 2, 5, 4, 2, 1, 6, 3, 9, 0],
       [0, 1, 2, 9, 3, 1, 3, 8, 5, 2, 1, 0],
       [0, 2, 3, 1, 1, 9, 4, 4, 5, 8, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## Sorting, Searching, Counting

### where

In [16]:
sub_m = matrix_2d[:3,:3]
print(sub_m)
print('---------')
print(np.where(sub_m < 3, 0, sub_m))

[[1 1 6]
 [1 3 8]
 [2 1 3]]
---------
[[0 0 6]
 [0 3 8]
 [0 0 3]]


### argwhere
Return positional indices of an array based on soem condition.

In [18]:
print(sub_m)
print('---------')
print(np.argwhere(sub_m > 4))

[[1 1 6]
 [1 3 8]
 [2 1 3]]
---------
[[0 2]
 [1 2]]
