# https://www.w3resource.com/python-exercises/basic/

### 1. Write a Python function that takes a sequence of numbers and determines if all the numbers are different from each other.

In [20]:
import numpy as np

np.random.seed(None)
nums = np.random.randint(0, 10, 5)
print(nums)

if len(nums) == len(set(nums)):
    print('Numbers are unique!')
else:
    print('Numbers NOT unique!')

[3 6 4 9 0]
Numbers are unique!


### 2. Write a Python program to create all possible strings by using 'a', 'e', 'i', 'o', 'u'. Use the characters exactly once.

In [44]:
import itertools

string = 'AEIOU'

all_strings = ["".join(perm) for perm in itertools.permutations(string)]
print(all_strings)

# check if all elements are unique
assert len(all_strings) == len(set(all_strings)), "Error!"

['AEIOU', 'AEIUO', 'AEOIU', 'AEOUI', 'AEUIO', 'AEUOI', 'AIEOU', 'AIEUO', 'AIOEU', 'AIOUE', 'AIUEO', 'AIUOE', 'AOEIU', 'AOEUI', 'AOIEU', 'AOIUE', 'AOUEI', 'AOUIE', 'AUEIO', 'AUEOI', 'AUIEO', 'AUIOE', 'AUOEI', 'AUOIE', 'EAIOU', 'EAIUO', 'EAOIU', 'EAOUI', 'EAUIO', 'EAUOI', 'EIAOU', 'EIAUO', 'EIOAU', 'EIOUA', 'EIUAO', 'EIUOA', 'EOAIU', 'EOAUI', 'EOIAU', 'EOIUA', 'EOUAI', 'EOUIA', 'EUAIO', 'EUAOI', 'EUIAO', 'EUIOA', 'EUOAI', 'EUOIA', 'IAEOU', 'IAEUO', 'IAOEU', 'IAOUE', 'IAUEO', 'IAUOE', 'IEAOU', 'IEAUO', 'IEOAU', 'IEOUA', 'IEUAO', 'IEUOA', 'IOAEU', 'IOAUE', 'IOEAU', 'IOEUA', 'IOUAE', 'IOUEA', 'IUAEO', 'IUAOE', 'IUEAO', 'IUEOA', 'IUOAE', 'IUOEA', 'OAEIU', 'OAEUI', 'OAIEU', 'OAIUE', 'OAUEI', 'OAUIE', 'OEAIU', 'OEAUI', 'OEIAU', 'OEIUA', 'OEUAI', 'OEUIA', 'OIAEU', 'OIAUE', 'OIEAU', 'OIEUA', 'OIUAE', 'OIUEA', 'OUAEI', 'OUAIE', 'OUEAI', 'OUEIA', 'OUIAE', 'OUIEA', 'UAEIO', 'UAEOI', 'UAIEO', 'UAIOE', 'UAOEI', 'UAOIE', 'UEAIO', 'UEAOI', 'UEIAO', 'UEIOA', 'UEOAI', 'UEOIA', 'UIAEO', 'UIAOE', 'UIEAO', 

### 3. Write a Python program to remove and print every third number from a list of numbers until the list becomes empty.

In [61]:
import numpy as np

nums = np.random.randint(0, 25, 20)
print(nums)
while len(nums) > 0:
    if len(nums) <= 2:
        nums = np.delete(nums, 0)
        print(nums)
    else:
        nums = np.delete(nums, 2)
        print(nums)

[22 15 10 15 13 13 22 20  8 15  1  8 23 18 16 13  5  0  7 10]
[22 15 15 13 13 22 20  8 15  1  8 23 18 16 13  5  0  7 10]
[22 15 13 13 22 20  8 15  1  8 23 18 16 13  5  0  7 10]
[22 15 13 22 20  8 15  1  8 23 18 16 13  5  0  7 10]
[22 15 22 20  8 15  1  8 23 18 16 13  5  0  7 10]
[22 15 20  8 15  1  8 23 18 16 13  5  0  7 10]
[22 15  8 15  1  8 23 18 16 13  5  0  7 10]
[22 15 15  1  8 23 18 16 13  5  0  7 10]
[22 15  1  8 23 18 16 13  5  0  7 10]
[22 15  8 23 18 16 13  5  0  7 10]
[22 15 23 18 16 13  5  0  7 10]
[22 15 18 16 13  5  0  7 10]
[22 15 16 13  5  0  7 10]
[22 15 13  5  0  7 10]
[22 15  5  0  7 10]
[22 15  0  7 10]
[22 15  7 10]
[22 15 10]
[22 15]
[15]
[]


### 4. Write a Python program to find unique triplets whose three elements gives the sum of zero from an array of n integers.

In [86]:
import numpy as np

def zero_triplets(array):
    give_zero = [comb for comb in itertools.combinations(array, 3) if sum(comb) == 0]
    return print(list(set(give_zero)))

nums = np.random.randint(-10, 10, 10)
print(nums,'\n')
zero_triplets(nums)

[  8   9   7 -10  -4   2  -2 -10   8  -4] 

[(8, -4, -4), (-10, 2, 8), (8, 2, -10), (8, -10, 2), (-4, 8, -4), (2, -10, 8)]


In [87]:
zero_triplets([1, -6, 4, 2, -1, 2, 0, -2, 0 ])

[(2, 0, -2), (2, -2, 0), (1, -1, 0), (-6, 4, 2)]


### 6. Write a Python program to print a long text, convert the string to a list and print all the words and their frequencies.

In [1]:
# 'string_words' : long string variable
string_words = '''United States Declaration of Independence
From Wikipedia, the free encyclopedia
The United States Declaration of Independence is the statement
adopted by the Second Continental Congress meeting at the Pennsylvania State
House (Independence Hall) in Philadelphia on July 4, 1776, which announced
that the thirteen American colonies, then at war with the Kingdom of Great
Britain, regarded themselves as thirteen independent sovereign states, no longer
under British rule. These states would found a new nation – the United States of
America. John Adams was a leader in pushing for independence, which was passed
on July 2 with no opposing vote cast. A committee of five had already drafted the
formal declaration, to be ready when Congress voted on independence.

John Adams persuaded the committee to select Thomas Jefferson to compose the original
draft of the document, which Congress would edit to produce the final version.
The Declaration was ultimately a formal explanation of why Congress had voted on July
2 to declare independence from Great Britain, more than a year after the outbreak of
the American Revolutionary War. The next day, Adams wrote to his wife Abigail: "The
Second Day of July 1776, will be the most memorable Epocha, in the History of America."
But Independence Day is actually celebrated on July 4, the date that the Declaration of
Independence was approved.

After ratifying the text on July 4, Congress issued the Declaration of Independence in
several forms. It was initially published as the printed Dunlap broadside that was widely
distributed and read to the public. The source copy used for this printing has been lost,
and may have been a copy in Thomas Jefferson's hand.[5] Jefferson's original draft, complete
with changes made by John Adams and Benjamin Franklin, and Jefferson's notes of changes made
by Congress, are preserved at the Library of Congress. The best-known version of the Declaration
is a signed copy that is displayed at the National Archives in Washington, D.C., and which is
popularly regarded as the official document. This engrossed copy was ordered by Congress on
July 19 and signed primarily on August 2.

The sources and interpretation of the Declaration have been the subject of much scholarly inquiry.
The Declaration justified the independence of the United States by listing colonial grievances against
King George III, and by asserting certain natural and legal rights, including a right of revolution.
Having served its original purpose in announcing independence, references to the text of the
Declaration were few in the following years. Abraham Lincoln made it the centerpiece of his rhetoric
(as in the Gettysburg Address of 1863) and his policies. Since then, it has become a well-known statement
on human rights, particularly its second sentence:

We hold these truths to be self-evident, that all men are created equal, that they are endowed by their
Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness.

This has been called "one of the best-known sentences in the English language", containing "the most potent
and consequential words in American history". The passage came to represent a moral standard to which
the United States should strive. This view was notably promoted by Abraham Lincoln, who considered the
Declaration to be the foundation of his political philosophy and argued that it is a statement of principles
through which the United States Constitution should be interpreted.

The U.S. Declaration of Independence inspired many other similar documents in other countries, the first
being the 1789 Declaration of Flanders issued during the Brabant Revolution in the Austrian Netherlands
(modern-day Belgium). It also served as the primary model for numerous declarations of independence across
Europe and Latin America, as well as Africa (Liberia) and Oceania (New Zealand) during the first half of the
19th century.'''

In [97]:
import collections

word_list = sorted(list(string_words.split(' ')))

frequencies = collections.Counter(word_list)

frequencies.most_common(3)

[('the', 43), ('of', 27), ('and', 13)]

### 8. Write a Python program to get the top stories from Google news.

In [57]:
from bs4 import BeautifulSoup as bs
import requests

# google news main page
url = 'https://news.google.com/?hl=en-US&gl=US&ceid=US:en'

r = requests.get(url)
soup = bs(r.text)

for i in soup.find_all('div', class_='ZulkBc qNiaOd'):
    try:
        print(i.find('h3').find('span').get_text())
    except AttributeError: # eliminates 'h4' possibilities
        continue

US stocks set to open lower amid renewed US-China tensions; Apple to report earnings
Democrats’ 2020 presidential contest is wide open as danger mounts for Trump, new Washington Post-ABC News poll shows
Kamala Harris defines her fight against Trump in CNN town hall
Our Dreams of Peace: Envisioning an End to War in Afghanistan
PG&E files for bankruptcy after California wildfires
Dem duo poses test for Trump, GOP | TheHill
Passenger stabs, kills pregnant Lyft driver in Tempe, Ariz.
Four Police Officers Shot in Houston Drug Raid
Guaido says he's still willing to consider amnesty for Maduro, military
Pakistan’s top court dismisses Islamists’ appeal to overturn Christian woman’s acquittal for blasphemy
Theresa May forces lawmakers to show their cards on Brexit
As Global Mining Fatalities Fall, Brazil Deaths Show Problems Remain
Nevada: Wynn Resorts Executives Ignored Sexual Misconduct Claims Against Steve Wynn
Here comes the earnings report Apple warned about — here's what to watch
CEO’s la

In [88]:
url2 = 'https://news.google.com/?hl=en-US&gl=US&ceid=US:en'
soup2 = bs(requests.get(url2).text)

x = soup2.find_all('div', class_='ZulkBc qNiaOd')

for news in x:
    try:
        print(news.h3.a.span.get_text())
        print('-'*20)
    except AttributeError:
        continue

Apple earnings; LVMH reports; Huawei charged
--------------------
'Huge selling point' for Kamala Harris is that she can go ‘crowd for crowd’ with Trump: Stirewalt
--------------------
Democrats’ 2020 presidential contest is wide open as danger mounts for Trump, new Washington Post-ABC News poll shows
--------------------
Our Dreams of Peace: Envisioning an End to War in Afghanistan
--------------------
PG&E files for bankruptcy after California wildfires
--------------------
Four Police Officers Shot in Houston Drug Raid
--------------------
Polar Vortex Clobbers Midwest With Record-Breaking Cold
--------------------
El Chapo too short to beat up rival gangsters: lawyer
--------------------
Brexit vote: Lawmakers try to force clarity over Theresa May's EU exit deal
--------------------
Guaido says he's still willing to consider amnesty for Maduro, military
--------------------
Pakistan blasphemy case ends with Aasia Bibi acquittal upheld, Christian woman free to leave today
----------

### 11. Write a Python program to check the sum of three elements (each from an array) from three arrays is equal to a target value. Print all those three-element combinations. Go to the editor

Sample data: <br>
X = [10, 20, 20, 20] <br>
Y = [10, 20, 30, 40] <br>
Z = [10, 30, 40, 20] <br>
target = 70 <br>

In [136]:
import numpy as np
import itertools

x = [10, 20, 20, 20]
y = [10, 20, 30, 40]
z = [10, 30, 40, 20]

target = 70

''' Return coordinate matrices from coordinate vectors.
    This provides all possible combinations of the three
    lists. Before reshape we transposed the matrix. The
    -1 in reshape acts as a placeholder for numpy to figure
    the shape out itself to be compatible with original matrix. '''
mesh = np.array(np.meshgrid(x, y, z)).T.reshape(-1, 3)
vals = [i for i in mesh if sum(i) == target]

# three element combiantions
print(np.unique(vals, axis=0))

[[10 20 40]
 [10 30 30]
 [10 40 20]
 [20 10 40]
 [20 20 30]
 [20 30 20]
 [20 40 10]]


### 12. Write a Python program to create all possible permutations from a given collection of distinct numbers.

In [141]:
import itertools

nums = [i for i in range(6)]
perms = [i for i in itertools.permutations(nums)]
len(perms)

720

### 13. Write a Python program to get all possible two digit letter combinations from a digit (1 to 9) string.

In [162]:
import itertools

def num_combs(num):
    string_maps = {
        "1": "abc",
        "2": "def",
        "3": "ghi",
        "4": "jkl",
        "5": "mno",
        "6": "pqrs",
        "7": "tuv",
        "8": "wxy",
        "9": "z"}
    
    strings = string_maps[str(num)[0]] + string_maps[str(num)[1]]
    combs = ["".join(i) for i in itertools.combinations(strings, 2)]
    print(combs)

In [163]:
num_combs(47)

['jk', 'jl', 'jt', 'ju', 'jv', 'kl', 'kt', 'ku', 'kv', 'lt', 'lu', 'lv', 'tu', 'tv', 'uv']


### 16. Write a Python program to get the third side of right angled triangle from two given sides.

In [227]:
from sympy.solvers import solve
from sympy import symbols

init_printing()

def third_side(cat1=None, cat2=None, hypo=None):
    '''Find the missing side of right triangle.'''
    
    if cat1 == cat2 == hypo == None:
        return print('Insert two arguments.')
    
    # variables
    args = {'cat1' : cat1, 'cat2' : cat2, 'hypo' : hypo}
    
    # which are the symbols
    cat1, cat2, hypo = symbols('cat1, cat2, hypo')
    
    # equation
    pyth_eq = cat1**2 + cat2**2 - hypo**2
    
    # solution
    solution = solve(pyth_eq.subs(args), dict=True)
    print(solution)

In [228]:
third_side(cat2 = 3, hypo=5)

[{cat1: -4}, {cat1: 4}]


In [226]:
from sympy import *

#  automatically enable the best printer available
init_printing()

x = Symbol('x')
solveset(sin(x) - 1, x, domain=S.Reals)

### 17. Write a Python program to get all strobogrammatic numbers that are of length n.

In [306]:
def strobogrammatic_numbers(n):
    '''Prints the list of n length strobogrammatic numbers.'''
    
    mirror = {"6" : '9', 
              "9" : '6'}
    
    exclude = '23457'
    
    strobos = []
    if n == 0:
        return print([])
    elif n == 1:
        return print(['0', '1', '8'])
    else:
        for number in range(10**(n-1), 10**n): 
            if any(i in str(number) for i in exclude):
                continue
            else:
                n = "".join([mirror[k] if k in mirror else k for k in str(number)])[::-1]
                if int(n) == number:
                    strobos.append(number)
    print(strobos)

In [307]:
for i in range(0,5):
    strobogrammatic_numbers(i)

[]
['0', '1', '8']
[11, 69, 88, 96]
[101, 111, 181, 609, 619, 689, 808, 818, 888, 906, 916, 986]
[1001, 1111, 1691, 1881, 1961, 6009, 6119, 6699, 6889, 6969, 8008, 8118, 8698, 8888, 8968, 9006, 9116, 9696, 9886, 9966]


### 20. Write a Python program to find the number of zeros at the end of a factorial of a given positive number.

In [7]:
from time import time
import math

# create a decorator for timing function execution time
def timer(func):
    def wrapper(*a, **kw):
        b4 = time()
        rv = func(*a, **kw) # rv : return value
        aft = time()
        
        # converting to appropriate second prefix
        units = ['s', 'ms', 'μs', 'ns', 'ps']
        n = float(aft-b4)
        index = max(0, min(len(units) - 1, 
                           int(abs(math.floor(0 if n == 0 else math.log10(abs(n)) / 3)))))
        print('\nElapsed time: {:.2f} {}'.format(n * 10 ** (index * 3), units[index]))
        return rv
    return wrapper

In [41]:
import math

@timer
def trailing_zeros(numb):
    '''Print factorial of the number and the number
    of its trailing zeros.'''
    
    x = math.factorial(numb)
    zeros = 0
    for i in range(len(str(x))):
        y = str(x)[::-1]
        if y[i] == '0':
            zeros += 1
        else:
            break
            
    print('{}! = {}'.format(numb, x))
    print('Trailing zeros count:', zeros)

In [51]:
trailing_zeros(40)

40! = 815915283247897734345611269596115894272000000000
Trailing zeros count: 9
Elapsed time: 161.17 μs


### 21. Write a Python program to find the number of notes (Sample of notes: 10, 20, 50, 100, 200 and 500 ) against an given amount. 
Range - Number of notes(n) : n (1 = n = 1000000).

In [72]:
@timer
def noting(amount):
    '''Prints the number of notes equivalent to specified amount.'''
    notes = [10, 20, 50, 100, 200, 500]
    dct = {}
    for note in notes[::-1]:
        if amount == 0:
            break
        else:
            x = amount // note
            amount = amount % note
            dct[str(note)] = x
    for k, v in dct.items():
        if v != 0:
            print(k, ':', v)
        else:
            continue

In [75]:
noting(113930)

500 : 227
200 : 2
20 : 1
10 : 1

Elapsed time: 388.15 μs


### 22. Write a Python program to create a sequence where the first four members of the sequence are equal to one, and each successive term of the sequence is equal to the sum of the four previous ones. Find the Nth member of the sequence.

In [79]:
@timer
def find_nth(n):
    '''Only print nth element. First element has index 1 (not 0)'''
    
    if n in range(1, 5):
        print('1')
    else:
        print(2 ** (n - 3))

In [87]:
find_nth(15)

4096

Elapsed time: 105.14 μs


In [148]:
@timer
def seq_and_nth(n):
    seq = [1,1,1,1]
    if n < 5 and n > 0:
        print("Sequence:\n", seq)
        print("\n{}th element is 1".format(n))
    else:
        for nr in range(1, n - 3):
            seq.append(sum(seq[-4:]))
    print("Sequence:\n", seq)
    print("\n{}th element is {}".format(n, seq[-1]))

In [149]:
seq_and_nth(16)

Sequence:
 [1, 1, 1, 1, 4, 7, 13, 25, 49, 94, 181, 349, 673, 1297, 2500, 4819]

16th element is 4819

Elapsed time: 243.19 μs


### 23. Write a Python program that accept a positive number and subtract from this number the sum of its digits and so on. Continues this operation until the number is positive.

In [104]:
from time import sleep

@timer
def numb_sub(number):
    '''Prints last remaining positive number from the sequence.'''
    
    print(number)
    while True:
        digit_sum = sum([int(digit) for digit in str(number)])
        number -= digit_sum
        if number <= 0:
            break
        else:
            print(number)

In [107]:
numb_sub(78)

78
63
54
45
36
27
18
9

Elapsed time: 401.02 μs


### 24. Write a Python program to find the number of divisors of a given integer is even or odd. 

In [18]:
@timer
def even_odd_divisors(n):
    nr_divs = len([i for i in range(2, n // 2) if n % i == 0 ])
    if nr_divs % 2 == 0 and nr_divs != 0:
        print('{} has even ({}) number of divisors.'.format(n, nr_divs))
    else:
        print('{} has odd ({}) number of divisors.'.format(n, nr_divs))

In [19]:
even_odd_divisors(53)

53 has odd (0) number of divisors.

Elapsed time: 73.91 μs


### 25. Write a Python program to find the digits which are absent in a given mobile number.

In [34]:
@timer
def absent_digits(number):
    x= [i for i in range(0, 10) if str(i) not in set(str(number))]
    print(x)

In [35]:
absent_digits(56471979)

[0, 2, 3, 8]

Elapsed time: 98.71 μs


## 26. Write a Python program to compute the summation of the absolute difference of all distinct pairs in an given array (non-decreasing order). Go to the editor

Sample array: [1, 2, 3] <br>
Then all the distinct pairs will be: <br>
1 2 <br>
1 3 <br>
2 3 <br>

In [7]:
import itertools

arr = [1, 4, 5]
# produce all combinations, no duplicates
combs = itertools.combinations(arr, 2)

abs_dif = [abs(i[0] - i[1]) for i in combs]
sum_abs_dif = sum(abs_dif)

print('{}\n{}\n{}'.format(arr, abs_dif, sum_abs_dif))

[1, 4, 5]
[3, 4, 1]
8


### 27. Write a Python program to find the type of the progression (arithmetic progression/geometric progression) and the next successive member of a given three successive members of a sequence.

According to Wikipedia, an arithmetic progression (AP) is a sequence of numbers such that the difference of any two successive members of the sequence is a constant. For instance, the sequence 3, 5, 7, 9, 11, 13, . . . is an arithmetic progression with common difference 2. For this problem, we will limit ourselves to arithmetic progression whose common difference is a non-zero integer.
On the other hand, a geometric progression (GP) is a sequence of numbers where each term after the first is found by multiplying the previous one by a fixed non-zero number called the common ratio. For example, the sequence 2, 6, 18, 54, . . . is a geometric progression with common ratio 3. For this problem, we will limit ourselves to geometric progression whose common ratio is a non-zero integer.

[162, 54, 18, 6, 2]